apiVersion: apps/v1
kind: Deployment
metadata:
  name: udmis-selfie
spec:
  selector:
    matchLabels:
      app: selfie
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: selfie
        role: master
        tier: backend
    spec:
      containers:
      - name: selfie-core
        image: @IMAGE-selfie@
        imagePullPolicy: Always
        env:
        - name: GCP_PROJECT
          value: @GCP_PROJECT@
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
